version: "3"

services:
  mongodb:
    image: "mongo:4.0"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER="user"
      - MONGODB_PASS="pass"
    volumes:
      - ./database/data:/data/db
    ports:
      - 27017:27017
    command: mongod
    restart: on-failure:5

  nginx:
    image: nginx:1.19.5
    volumes:
      - ./deployments/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8082:8082"
    network_mode: "host"
    restart: on-failure:5

  prom:
    image: prom/prometheus:v2.1.0
    volumes:
      - ./telemetry/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    restart: on-failure:5