version: "3"

services:
  mongodb:
    image: "mongo:4.0"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER="user"
      - MONGODB_PASS="pass"
    volumes:
      - ./database/data:/data/db
    ports:
      - 27017:27017
    command: mongod
    restart: on-failure:5

  fastapi_server:
    build: model/api/
    volumes:
      - ./model/dataset:/dataset
      - ./model/checkpoint:/checkpoint
    ports:
      - "8082:80"
    restart: on-failure:5
