name: Push to a branch

on: [push]

jobs:
  run:
    runs-on: ubuntu-18.04

    env:
      OS: "ubuntu-18.04"
      PYTHON: "3.7"

    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run tests
      run: |
        coverage run -m pytest && coverage report -m